---
title: "p8105_hw5_jak2312"
author: "Jared Klug"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
```

## Problem 1

Read and clean df
```{r}
homicide_df = 
  read_csv("./data/homicide/homicide-data.csv") %>% 
  mutate(
    resolved = case_when(
      disposition == "Closed without arrest" ~ "unsolved",
      disposition == "Open/No arrest" ~ "unsolved",
      disposition == "Closed by arrest" ~ "solved"
    ),
    city_state = str_c(city, state, sep = "_")
  ) %>% 
  select(city_state, resolved) %>% 
  filter(city_state != "Tulsa_AL")
```

create aggregate df
```{r}
aggregate_df = 
  homicide_df %>% 
    group_by(city_state) %>% 
    summarize(
      hom_total = n(),
      hom_unsolved = sum(resolved == "unsolved")
    ) 
```

run prop test for 1 city
```{r}
prop.test(
  aggregate_df %>% filter(city_state == "Baltimore_MD") %>% pull(hom_unsolved),
  aggregate_df %>% filter(city_state == "Baltimore_MD") %>% pull(hom_total)
) %>% broom::tidy()
```

itterate over all the cities
```{r}
results_df = 
  aggregate_df %>% 
    mutate(
      prop_test = map2(.x = hom_unsolved, .y = hom_total, ~prop.test(x = .x, n = .y)),
      tidy_test = map(prop_test, broom::tidy)
    ) %>% 
    select(-prop_test) %>% 
    unnest(tidy_test) %>% 
    select(city_state, estimate, conf.low, conf.high)
```

Arrange by estimate
```{r}
results_df %>% 
  mutate(city_state = fct_reorder(city_state, estimate)) %>% 
  ggplot(aes(x = city_state, y = estimate)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```


